name = "circlek-api"
main = "worker.js"
compatibility_date = "2024-07-18"

[[kv_namespaces]]
binding = "REDEEMED"
id = "redeemed_items"

[[kv_namespaces]]
binding = "BUGS"
id = "bug_reports"

[[kv_namespaces]]
binding = "STATUS"
id = "working_status"

[vars]
# No environment variables needed
